import { supabase } from "../supabaseClient";
import bcrypt from "bcryptjs";

// Record student login for reporting
// Record student login for reporting - FIXED for your table structure
export const recordStudentLogin = async (studentData) => {
  try {
    const today = new Date();
    const loginDate = today.toISOString().split('T')[0]; // YYYY-MM-DD
    const loginTime = today.toTimeString().split(' ')[0]; // HH:MM:SS

    console.log("Attempting to record login for:", studentData.student_id);

    // Check if student already logged in today using student_id
    const { data: existingLog, error: checkError } = await supabase
      .from("login_reports")
      .select("id")
      .eq("student_id", studentData.student_id)
      .eq("login_date", loginDate)
      .maybeSingle();

    if (checkError) {
      console.error("Error checking existing login:", checkError);
      return;
    }

    // If no record exists for today, insert new login record
    if (!existingLog) {
      console.log("Inserting new login record for:", studentData.student_id);
      
      const { error } = await supabase
        .from("login_reports")
        .insert([
          {
            student_id: studentData.student_id,  // Use student_id only (no student_uuid)
            first_name: studentData.first_name,
            last_name: studentData.last_name,
            login_date: loginDate,
            login_time: loginTime,
            // created_at will be auto-generated by default value
          },
        ]);

      if (error) {
        console.error("Error recording login:", error);
      } else {
        console.log("✅ Login recorded successfully for:", studentData.student_id);
      }
    } else {
      console.log("Student already logged in today:", studentData.student_id);
    }
  } catch (error) {
    console.error("Failed to record login:", error);
  }
};

// LOGIN - Compare hashed password
export const loginStudent = async (studentId, password) => {
  try {
    const { data, error } = await supabase
      .from("students")
      .select("*")
      .eq("student_id", studentId)
      .single();

    if (error || !data) {
      console.error("Login error:", error);
      return { success: false, message: "Invalid login credentials" };
    }

    // Compare the provided password with the hashed password
    const isPasswordValid = await bcrypt.compare(password, data.password);
    
    if (!isPasswordValid) {
      return { success: false, message: "Invalid login credentials" };
    }

    // Record the login (don't await to not delay login response)
    recordStudentLogin(data).catch(err => 
      console.error("Background login recording failed:", err)
    );

    // Remove password from returned data
    const { password: _, ...userWithoutPassword } = data;
    
    return { 
      success: true, 
      data: userWithoutPassword,
      message: "Login successful" 
    };
  } catch (error) {
    console.error("Login error:", error);
    return { success: false, message: "An error occurred during login" };
  }
};

// REGISTER - Hash password before storing
export const registerStudent = async (form) => {
  try {
    // Check if student ID already exists
    const { data: existing, error: checkError } = await supabase
      .from("students")
      .select("student_id")
      .eq("student_id", form.studentId)
      .maybeSingle();

    if (checkError) {
      console.error("Error checking student ID:", checkError);
      return { success: false, message: "Error checking student ID" };
    }

    if (existing) {
      return { success: false, message: "Student ID already registered" };
    }

    // Hash the password
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash(form.password, saltRounds);

    // Insert new student with hashed password
    const { data, error } = await supabase
      .from("students")
      .insert([
        {
          student_id: form.studentId,
          first_name: form.firstName,
          middle_name: form.middleName || null,
          last_name: form.lastName,
          course: form.course,
          password: hashedPassword,
        },
      ])
      .select()
      .single();

    if (error) {
      console.error("Registration error:", error);
      return { success: false, message: error.message };
    }

    return { 
      success: true, 
      data,
      message: "Registration successful" 
    };
  } catch (error) {
    console.error("Registration error:", error);
    return { success: false, message: "Error creating account" };
  }
};

// Get student by ID
export const getStudentById = async (studentId) => {
  try {
    const { data, error } = await supabase
      .from("students")
      .select("id, student_id, first_name, middle_name, last_name, course")
      .eq("student_id", studentId)
      .single();

    if (error) {
      console.error("Error fetching student:", error);
      return { success: false, message: "Student not found" };
    }

    return { success: true, data };
  } catch (error) {
    console.error("Error fetching student:", error);
    return { success: false, message: "Error fetching student data" };
  }
};

// Get all students
export const getAllStudents = async () => {
  try {
    const { data, error } = await supabase
      .from("students")
      .select("id, student_id, first_name, middle_name, last_name, course")
      .order("last_name", { ascending: true });

    if (error) {
      console.error("Error fetching students:", error);
      return { success: false, message: "Error fetching students" };
    }

    return { success: true, data };
  } catch (error) {
    console.error("Error fetching students:", error);
    return { success: false, message: "Error fetching students" };
  }
};

// Update student
export const updateStudent = async (studentId, updates) => {
  try {
    // Remove password from updates if it's empty
    if (updates.password && updates.password.trim() === "") {
      delete updates.password;
    }

    // If password is being updated, hash it
    if (updates.password) {
      const saltRounds = 10;
      updates.password = await bcrypt.hash(updates.password, saltRounds);
    }

    const { data, error } = await supabase
      .from("students")
      .update(updates)
      .eq("student_id", studentId)
      .select()
      .single();

    if (error) {
      console.error("Error updating student:", error);
      return { success: false, message: error.message };
    }

    // Remove password from returned data
    const { password: _, ...studentWithoutPassword } = data;

    return { 
      success: true, 
      data: studentWithoutPassword,
      message: "Student updated successfully" 
    };
  } catch (error) {
    console.error("Error updating student:", error);
    return { success: false, message: "Error updating student" };
  }
};

// Delete student
export const deleteStudent = async (studentId) => {
  try {
    // Note: Login reports will be automatically deleted due to ON DELETE CASCADE
    const { error } = await supabase
      .from("students")
      .delete()
      .eq("student_id", studentId);

    if (error) {
      console.error("Error deleting student:", error);
      return { success: false, message: error.message };
    }

    return { 
      success: true, 
      message: "Student deleted successfully" 
    };
  } catch (error) {
    console.error("Error deleting student:", error);
    return { success: false, message: "Error deleting student" };
  }
};

// Get login reports with filters - UPDATED for your table structure
export const getLoginReports = async (filters = {}) => {
  try {
    let query = supabase
      .from("login_reports")
      .select("*")
      .order("login_date", { ascending: false })
      .order("login_time", { ascending: false });

    // Apply filters
    if (filters.startDate) {
      query = query.gte("login_date", filters.startDate);
    }
    if (filters.endDate) {
      query = query.lte("login_date", filters.endDate);
    }
    if (filters.studentId) {
      query = query.eq("student_id", filters.studentId);
    }

    const { data, error } = await query;

    if (error) {
      console.error("Error fetching login reports:", error);
      return { success: false, message: "Error fetching login reports" };
    }

    return { success: true, data };
  } catch (error) {
    console.error("Error fetching login reports:", error);
    return { success: false, message: "Error fetching login reports" };
  }
};

// Get login statistics - UPDATED for your table structure
export const getLoginStatistics = async (days = 7) => {
  try {
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days);

    const { data, error } = await supabase
      .from("login_reports")
      .select("*")
      .gte("login_date", startDate.toISOString().split('T')[0])
      .lte("login_date", endDate.toISOString().split('T')[0]);

    if (error) {
      console.error("Error fetching statistics:", error);
      return { success: false, message: "Error fetching statistics" };
    }

    // Process statistics
    const dailyStats = {};
    const hourlyDistribution = Array(24).fill(0);
    
    data.forEach(record => {
      // Daily stats
      if (!dailyStats[record.login_date]) {
        dailyStats[record.login_date] = {
          date: record.login_date,
          total: 0,
          uniqueStudents: new Set()
        };
      }
      dailyStats[record.login_date].total++;
      dailyStats[record.login_date].uniqueStudents.add(record.student_id); // Use student_id instead of student_uuid

      // Hourly distribution
      const hour = parseInt(record.login_time.split(':')[0]);
      hourlyDistribution[hour]++;
    });

    // Convert Sets to counts
    Object.values(dailyStats).forEach(stat => {
      stat.uniqueStudents = stat.uniqueStudents.size;
    });

    return { 
      success: true, 
      data: {
        daily: Object.values(dailyStats),
        hourly: hourlyDistribution,
        total: data.length,
        uniqueStudents: new Set(data.map(r => r.student_id)).size // Use student_id
      }
    };
  } catch (error) {
    console.error("Error processing statistics:", error);
    return { success: false, message: "Error processing statistics" };
  }
};